/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.search;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Jane Chew
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUserName = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jbtnRegister = new javax.swing.JButton();
        jlblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblPassword1 = new javax.swing.JLabel();
        jtxtPassword1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblUserName.setText("UserName : ");

        jlblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPassword.setText("password :");

        jtxtUserName.setToolTipText("");
        jtxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserNameActionPerformed(evt);
            }
        });

        jbtnRegister.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnRegister.setText("Register");
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });

        jlblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMessage.setText("Please enter your username and password.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration");

        jlblPassword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPassword1.setText("re-enter password :");

        jtxtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPassword1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblUserName)
                                    .addComponent(jlblPassword))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtUserName)
                                    .addComponent(jtxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblPassword1)
                                .addGap(32, 32, 32)
                                .addComponent(jtxtPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jbtnRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUserName)
                    .addComponent(jtxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPassword)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPassword1)
                    .addComponent(jtxtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jbtnRegister)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterActionPerformed
        // TODO add your handling code here:

        String username = jtxtUserName.getText();
        String name = jtxtUserName.getText();
        String password = jtxtPassword.getText();
        String repassword = jtxtPassword1.getText();
        String position = "customer";
        
        
        //UserDatabase[] customer = new UserDatabase(position, name, username, password);
        
        Pattern p = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
        Pattern digitCasePattern = Pattern.compile("[0-9]");
        Pattern charCasePattern = Pattern.compile("[a-zA-Z]+");
        Matcher m = p.matcher(username);
        boolean b = m.find();
         
        /*if(jtxtPassword.getText().equals("") && jtxtUserName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username and password cannot be empty","Error",2);
            
        }
        
        else if(jtxtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "password cannot be empty","Error",2);
            
        }
        else if(jtxtUserName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username cannot be empty","Error",2);
            
        }
        if(!password.equals(repassword)){
            JOptionPane.showMessageDialog(null, "The passwords do not match, please try again","Error",2);
        }
        if(jtxtPassword.getText() != "" && jtxtUserName.getText()!=""){
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(position,name,username,password).setVisible(true);
            }
        });
            this.setVisible(false);
        }*/
        
        int length = password.length();
        if("".equals(username) || "".equals(password) || "".equals(repassword)){
            JOptionPane.showMessageDialog(this, "username or password is not allowed to left bank.", "Error", 2);
        }
        else if(b){
            JOptionPane.showMessageDialog(this, "username cannot contain special characters", "Error", 2);
        }
        else if(length <= 6){
            JOptionPane.showMessageDialog(this, "password should more than 6 charaters", "Error", 2);
        }
        else if(!digitCasePattern.matcher(password).find()){
            JOptionPane.showMessageDialog(this, "password should contain digits", "Error", 2);
        }
        else if(!charCasePattern.matcher(password).find()){
            JOptionPane.showMessageDialog(this, "password should contain characters", "Error", 2);
        }
        else if(!password.equals(repassword)){
            JOptionPane.showMessageDialog(this, "password and re-enter password are not same. Please input again", "Error", 2);
        }
        else{
            new Login(position, name, username, password).setVisible(true);
            this.setVisible(false);
        }
         
         
         
         
        

         


    }//GEN-LAST:event_jbtnRegisterActionPerformed

    private void jtxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserNameActionPerformed

    private void jtxtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JLabel jlblMessage;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblPassword1;
    private javax.swing.JLabel jlblUserName;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JPasswordField jtxtPassword1;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
}
