/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.search;

import java.awt.Color;
import java.awt.Graphics2D;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author OEM
 */
public class AddProductUI extends javax.swing.JFrame {
    ProductADT product1 = new ProductList();
    
    //save
    public ProductListUI showList;
    


    /**
     * Creates new form UserInterface
     */
    public AddProductUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblName = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jlblCat = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JLabel();
        jbtnDisplay = new javax.swing.JButton();
        jtxtName = new javax.swing.JTextField();
        jtxtPrice = new javax.swing.JTextField();
        jbtnUpload = new javax.swing.JButton();
        jlblImgIcon = new javax.swing.JLabel();
        jlblTitle = new javax.swing.JLabel();
        jlblDesc = new javax.swing.JLabel();
        jtxtDesc = new javax.swing.JScrollPane();
        jtxtDescription = new javax.swing.JTextArea();
        jcmbCategory = new javax.swing.JComboBox<>();
        jlblBarcode = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jbtnRemove = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jlblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblName.setText("Name :");

        jbtnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jlblCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblCat.setText("Category :");

        jlblPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPrice.setText("Price :");

        jbtnDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDisplay.setText("Display Product List");
        jbtnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDisplayActionPerformed(evt);
            }
        });

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jbtnUpload.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnUpload.setText("Upload");
        jbtnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUploadActionPerformed(evt);
            }
        });

        jlblImgIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblTitle.setBackground(new java.awt.Color(255, 255, 255));
        jlblTitle.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText("Add Product");
        jlblTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblDesc.setText("Description : ");

        jtxtDesc.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jtxtDesc.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jtxtDescription.setColumns(20);
        jtxtDescription.setRows(5);
        jtxtDesc.setViewportView(jtxtDescription);
        jtxtDescription.getAccessibleContext().setAccessibleParent(this);

        jcmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Razor", "Shampoo", "Toothbrush", "Toothpaste" }));
        jcmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCategoryActionPerformed(evt);
            }
        });

        jlblBarcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblBarcode.setText("Product ID  :");
        jlblBarcode.setEnabled(false);

        jtxtID.setEnabled(false);

        jbtnRemove.setText("Remove item");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jbtnUpload))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jlblImgIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblPrice)
                                    .addComponent(jlblDesc))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jbtnRemove)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblCat)
                                    .addComponent(jlblName)
                                    .addComponent(jlblBarcode))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtName, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jcmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtID)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jbtnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jlblImgIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblBarcode)
                            .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblName)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCat)
                            .addComponent(jcmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblDesc)
                            .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblPrice)
                            .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUpload)
                    .addComponent(jbtnRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        String name = jtxtName.getText();
        String category = jcmbCategory.getSelectedItem().toString();
        String description = jtxtDescription.getText();
        double price = Double.parseDouble(jtxtPrice.getText());
   
        product1 = new ProductList(name, category, description, price);

        jtxtID.setText("");
        jtxtName.setText("");
        jtxtDescription.setText("");
        jtxtPrice.setText("");
        jlblImgIcon.setIcon(new ImageIcon());
        jtxtName.grabFocus();

    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDisplayActionPerformed
        // TODO add your handling code here:
        
        //JOptionPane.showMessageDialog(null, formatList());
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductListUI().setVisible(true);
            }
        });
        this.setVisible(false); */
        //JFrame f= new JFrame(); 
        
        //DefaultListModel<String> l1 = new DefaultListModel<>();  
        
     /*DefaultListModel listModel = new DefaultListModel();
        JList list = new JList(listModel);
        
        listModel.add(productL.getName());*/
        
        /*for (int i = 0; i < count; i++){
            l1.addElement(product[i].getName());
        }
        


          /*l1.addElement("Item1");  
          l1.addElement("Item2");  
          l1.addElement("Item3");  
          l1.addElement("Item4");  
          JList<String> list = new JList<>(l1);  
          list.setBounds(0,0, 50,50);  
         
          /*f.add(list);  
          f.setSize(563, 557);  
          f.setLayout(null);  
          f.setVisible(true);  *
 
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           // new ProductListUI().jListDisplayName.add(list);
            //new ProductListUI().jListDisplayName.setSize(200,200);
            
            new ProductListUI(list).setVisible(true);
            }
        });*/
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           new ProductListUI().setVisible(true);
        
        }
        });
           this.setVisible(false);
    }//GEN-LAST:event_jbtnDisplayActionPerformed

    private void jbtnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileUp = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("3 Extensions Supported", "jpg", "png", "jpeg");
        fileUp.setFileFilter(fil);
        int imgSelected = fileUp.showOpenDialog(this);
        if(imgSelected == fileUp.APPROVE_OPTION){
            File filePC = fileUp.getSelectedFile();
            String getImgSelected = filePC.getAbsolutePath();
            JOptionPane.showMessageDialog(this, "Image upload successfully from directory: '" + getImgSelected + "'.");
            ImageIcon imgIcon = new ImageIcon(getImgSelected);
            //Stretch image to fit
            Image imgFit = imgIcon.getImage();
            imgFit = imgFit.getScaledInstance(jlblImgIcon.getWidth(), jlblImgIcon.getHeight(), Image.SCALE_SMOOTH);
            jlblImgIcon.setIcon(new ImageIcon(imgFit));
        }
    }//GEN-LAST:event_jbtnUploadActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jcmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCategoryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcmbCategoryActionPerformed

    public String formatList() {
        //bug-only show the last product details
        //show only all product names which can be selected
        String outputStr = "";
            
        /*outputStr = "No.        Name            Brand           Price\n";
        
        for (int i = 0; i < count; i++) {
            outputStr += (i + 1) + ".           " + product.getName() + "           " 
                    + product.getBrand() + "            " 
                    + product.getPrice() + "\n";
        }*/
        
       /* outputStr = "No.        Name \n";
        for (int i = 0; i < count; i++){
            outputStr += (i + 1) + ".          " + product[i].getName() + "\n";
        }
        
        return outputStr;
        */
        
        
        //return System.out.println(product.toString());
       // return product.print();
        //return "Hello world";
        return null;
  }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>    
        //</editor-fold>    
            
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDisplay;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnUpload;
    private javax.swing.JComboBox<String> jcmbCategory;
    private javax.swing.JLabel jlblBarcode;
    private javax.swing.JLabel jlblCat;
    private javax.swing.JLabel jlblDesc;
    private javax.swing.JLabel jlblImgIcon;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JScrollPane jtxtDesc;
    private javax.swing.JTextArea jtxtDescription;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPrice;
    // End of variables declaration//GEN-END:variables

}
