/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.search;

import javax.swing.JOptionPane;

/**
 *
 * @author OEM
 */
public class Login extends javax.swing.JFrame {
    public UserDatabase[] user = new UserDatabase[10];
    public int UserCount;
    public boolean UserCheck = false;
    private String username;
    private String password;
    private int CustomerCount = -1;
    private int StaffCount;
    UserDatabase[] staff = new UserDatabase[5];
    UserDatabase[] customer = new UserDatabase[5];
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        UserCheck = false;
    }
    
    public Login(String position, String name, String username, String password){
        initComponents();
        UserCheck = false;
        CustomerCount ++;
        customer[CustomerCount] = new UserDatabase(position, name, username, password);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jlblUserName = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jlblMessage = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        jbtnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText("Login");

        jlblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblUserName.setText("UserName : ");

        jlblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPassword.setText("password :");

        jtxtUserName.setToolTipText("");
        jtxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserNameActionPerformed(evt);
            }
        });

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jlblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMessage.setText("Please enter your username and password.");

        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });

        jbtnRegister.setText("Register");
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblUserName)
                            .addComponent(jlblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtUserName)
                            .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jbtnRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnLogin)
                        .addGap(107, 107, 107)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUserName)
                    .addComponent(jtxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPassword)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogin)
                    .addComponent(jbtnRegister))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        
        //Admin account//
        UserCheck = false;
        staff[0] = new UserDatabase("staff", "horyee", "horyee", "horyee123");
        staff[1] = new UserDatabase("staff", "qingxiang", "qingxiang", "qingxiang123");
        staff[2] = new UserDatabase("staff", "choonyik", "choonyik", "choonyik123");
        StaffCount = 2;
        
        //Customer account//

        customer[CustomerCount + 1] = new UserDatabase("customer", "jane", "jane", "jane123");
        customer[CustomerCount + 2] = new UserDatabase("customer", "keyzhoun", "keyzhoun", "keyzhoun123");
        CustomerCount= +2;
        
        username = jtxtUserName.getText();
        password = jtxtPassword.getText();
        
        //Check customer login
        for(int i=0 ; i<CustomerCount ; i++){
            if(username.equals(customer[i].getName())){
                if(password.equals(customer[i].getPassword())){
                    jlblMessage.setText("Login Success");
                    UserCheck = true;
                    //new AddProductUI().setVisible(true);
                   // this.setVisible(false);
                }
               
            }
             
                
        }
        
        //int j = 0;
        //Check staff login
       // while(UserCheck == false){
        for(int i=0 ; i<StaffCount ; i++){
            if(username.equals(staff[i].getName())){
                if(password.equals(staff[i].getPassword())){
                    jlblMessage.setText("Login Success");
                    UserCheck = true;
                    //new AddProductUI().setVisible(true);
                    //this.setVisible(false);
                }
                //else {
                   // JOptionPane.showMessageDialog(this, "Incorrect username and password. "
                     //       + "\nPlease enter your username and passsword again.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    
                //}
            }
        }
        //}
        
        /*for(int i=0 ; i<UserCount ; i++){
            if(username.equals("jane")){
                if(password.equals("jane")){
                    jlblMessage.setText("Login Success");
                    UserCheck = true;
                    new AddProductUI().setVisible(true);
                    this.setVisible(false);
                }
            }
   
        }*/
        //UserCheck = false;
        if(UserCheck == false){
             jlblMessage.setText("Incorrect UserName or password");
        }
        else if (UserCheck == true){
            jlblMessage.setText("Login Success");
            new AddProductUI().setVisible(true);
            this.setVisible(false);
            
        }
        
        
        if(jtxtPassword.getText().equals("") && jtxtUserName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username and password cannot be empty","Error",2);
            
        }
        
        else if(jtxtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "password cannot be empty","Error",2);
            
        }
        else if(jtxtUserName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username cannot be empty","Error",2);
            
        }
        
        
        
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterActionPerformed
        // TODO add your handling code here:
        
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Register().setVisible(true);
                }
            });
        
        this.setVisible(false);
    }//GEN-LAST:event_jbtnRegisterActionPerformed

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jtxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Login().setVisible(true);
                }
            });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JLabel jlblMessage;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlblUserName;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
}
