/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.search;

import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author OEM
 */
public class ProductListUI extends javax.swing.JFrame {
    public ProductADT[] product1 = new ProductList[20];
    int size = 6;
    
    DefaultListModel listModel = new DefaultListModel();
    
    Random dice = new Random();
    String searchType = "name";
    String searchContent = "";
   //jList p =new jList();
    /**
     * Creates new form ProductNameLists
     */
    //ProductList productL;
    
    public ProductListUI() {
       initComponents();        
       //AddProductUI p = new AddProductUI();       
       //jLabel1.setText(p.product1.getName());
       //String searchType = "name";
        //  String searchContent = "";
        addList();
    }
    
    public ProductListUI(String name, String category, String description, double price, int barcode) {
        initComponents();
        
        product1[0] = new ProductList(name, category, description, price, barcode);
        addProduct(product1[0].getName());
    }

    private void addList(){        
        //jListProduct.clearSelection();
        ProductArray();
        for(int i = 0 ; i < size ; i ++){
            if(searchType.equals("name")){
                if(searchContent.equals("")||searchContent.equals(product1[i].getName())){
                    addProduct(product1[i].getName());
                }
            }
        }
    }
    
    private void addProduct(String name){
        jListProduct.setModel(listModel);
        //listModel.addElement("Name\t\tCategory\tDescription");
        //String searchType = "name";
        //  String searchContent = "";
        
        String output = name;
        listModel.addElement(output);
    }
    
     public ProductListUI(boolean status) {
       initComponents();
       if(status == false){
           System.out.println(status);
       jbtnAdd.setVisible(false);
       jbtnAdd.setEnabled(status);
       jbtnUpdate.setVisible(false);
       jbtnSearch.setVisible(false);
       }
       else{
       jcmbSelection.setVisible(false);
       }
       
       
    }
    
    public void ProductArray(){
        product1[0] = new ProductList("SUNSILK", "Shampoo", "Soft and smooth shampoo 650ml", 26.50,140121);
        product1[1] = new ProductList("PANTENE", "Shampoo", "Shampoo anti Dandruff 340ml", 11.00,140122);
        product1[2] = new ProductList("ORAL-B", "Complete", "HE", 25,140231);
        product1[3] = new ProductList("HE", "HE", "HE", 25,111111);
        product1[4] = new ProductList("HE", "HE", "HE", 25,111112);
        product1[5] = new ProductList("HE", "HE", "HE", 25,111113);        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListProduct = new javax.swing.JList();
        jlblTitle = new javax.swing.JLabel();
        jbtnAdd = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnGenerate = new javax.swing.JButton();
        jcmbCategory = new javax.swing.JComboBox();
        jcmbBrand = new javax.swing.JComboBox();
        jtxtBarcode = new javax.swing.JTextField();
        jlblBarcode = new javax.swing.JLabel();
        jcmbAttribute = new javax.swing.JComboBox();
        jbtnSearch = new javax.swing.JButton();
        jcmbSelection = new javax.swing.JComboBox();
        jPanelPrice = new javax.swing.JPanel();
        jRadBtn10 = new javax.swing.JRadioButton();
        jRadBtn15 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTxtPriceMin = new javax.swing.JTextField();
        jTxtPriceMax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListProduct);

        jlblTitle.setBackground(new java.awt.Color(255, 255, 255));
        jlblTitle.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText("Product Lists");
        jlblTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnGenerate.setText("Generate barcode");
        jbtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateActionPerformed(evt);
            }
        });

        jcmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "HE", "Item 3", "Item 4" }));
        jcmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCategoryActionPerformed(evt);
            }
        });

        jcmbBrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brand Name", "Item 2", "Item 3", "Item 4" }));

        jtxtBarcode.setToolTipText("");

        jlblBarcode.setText("Barcode : ");

        jcmbAttribute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Attribute", "Item 2", "Item 3", "Item 4" }));

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jcmbSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Category", "Brand Name", "Attribute", "Barcode" }));
        jcmbSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbSelectionActionPerformed(evt);
            }
        });

        jPanelPrice.setBorder(javax.swing.BorderFactory.createTitledBorder("Price Range: "));
        jPanelPrice.setToolTipText("");
        jPanelPrice.setName(""); // NOI18N

        jRadBtn10.setText("MYR1 - MYR10");

        jRadBtn15.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        javax.swing.GroupLayout jPanelPriceLayout = new javax.swing.GroupLayout(jPanelPrice);
        jPanelPrice.setLayout(jPanelPriceLayout);
        jPanelPriceLayout.setHorizontalGroup(
            jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadBtn10)
                    .addComponent(jRadBtn15)
                    .addComponent(jRadioButton2))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelPriceLayout.setVerticalGroup(
            jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadBtn10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTxtPriceMin.setToolTipText("Enter Price Range");
        jTxtPriceMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPriceMinKeyTyped(evt);
            }
        });

        jTxtPriceMax.setToolTipText("Enter Price Range");
        jTxtPriceMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPriceMaxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcmbSelection, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcmbBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcmbAttribute, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jbtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTxtPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcmbSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jcmbAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtBarcode)
                                    .addComponent(jlblBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public void custBtnDisable(){
        jbtnAdd.setVisible(false);
        jbtnDelete.setVisible(false);
        jbtnUpdate.setVisible(false);
        jbtnGenerate.setVisible(false);
        searchBtnDisable();
    }
    
        public void searchBtnDisable(){
            jcmbSelection.setVisible(false);
            jcmbCategory.setVisible(false);
            jcmbBrand.setVisible(false);
            jcmbAttribute.setVisible(false);
            jlblBarcode.setVisible(false);
            jtxtBarcode.setVisible(false);
        }
    
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        //UserInterface.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductUI().setVisible(true);
            }
        });
        this.setVisible(false);

    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
       // jListDisplayName.remove;
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductUI(product1[0].getName()).setVisible(true);
            }
        });
        this.setVisible(false);
        
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateActionPerformed
        // TODO add your handling code here:
            if(product1[0] == null){
                JOptionPane.showMessageDialog(null, "No item selected to generate barcode!","Error",2);
              
            }
            else{
                String barcode;
        
        
        barcode = "PA010" + dice.nextInt(6);
        
                 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductUI(product1[0].getName(),barcode).setVisible(true);
            }
        });
        this.setVisible(false);
            }
        
        
    }//GEN-LAST:event_jbtnGenerateActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        // TODO add your handling code here:
                searchBtnDisable();
        jcmbSelection.setVisible(true);
        
        //vvvvvvvvvv  priceRange filter  vvvvvvvvvv
        int priceMin = Integer.parseInt(jTxtPriceMin.getText());
        int priceMax = Integer.parseInt(jTxtPriceMax.getText());
        if(priceMax < priceMin){
            JOptionPane.showMessageDialog(null, "Max price must be higher than min price! ", "Error", 2);
            jTxtPriceMax.setText("");jTxtPriceMax.grabFocus();
        }else if(priceMin < priceMax){
            listModel.clear();//clear List
            for(int k=0;k<size;k++){
                if(product1[k].getPrice() <= priceMax && product1[k].getPrice() >= priceMin){
                    addProduct(product1[k].getName());
                }
            }
        }
        //^^^^^^^^^^  priceRange filter  ^^^^^^^^^^
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jcmbSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbSelectionActionPerformed
        // TODO add your handling code here:
        String selection = jcmbSelection.getModel().getSelectedItem().toString();
        
        if(selection.equals("Category")){
            jcmbCategory.setVisible(true);
        }
        else if(selection.equals("Brand Name")){
            jcmbBrand.setVisible(true);
        }
        else if(selection.equals("Attribute")){
            jcmbAttribute.setVisible(true);
        }
        else if(selection.equals("Barcode")){
            jlblBarcode.setVisible(true);
            jtxtBarcode.setVisible(true);
        }
        
        
        jcmbSelection.setVisible(false);
    }//GEN-LAST:event_jcmbSelectionActionPerformed

    private void jcmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCategoryActionPerformed
        // TODO add your handling code here:
        String category = jcmbCategory.getModel().getSelectedItem().toString();
        if(category.equals("HE")){
           searchContent = "HE";
        }


        addList();

        
    }//GEN-LAST:event_jcmbCategoryActionPerformed

    private void jTxtPriceMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPriceMinKeyTyped
        //vvvvvvvvvv   priceRange Force Number input(Min Price)   vvvvvvvvvv
        char price = evt.getKeyChar();
        if(!(Character.isDigit(price))
            ||(price == KeyEvent.VK_BACK_SPACE)
            ||(price == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }//^^^^^^^^^^   priceRange Force Number input(Min Price)   ^^^^^^^^^^
    }//GEN-LAST:event_jTxtPriceMinKeyTyped

    private void jTxtPriceMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPriceMaxKeyTyped
        //vvvvvvvvvv   priceRange Force Number input(Max Price)   vvvvvvvvvv
        char price = evt.getKeyChar();
        if(!(Character.isDigit(price))
            ||(price == KeyEvent.VK_BACK_SPACE)
            ||(price == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }//^^^^^^^^^^   priceRange Force Number input(Max Price)   ^^^^^^^^^^
    }//GEN-LAST:event_jTxtPriceMaxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        

        
        java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
         new ProductListUI().setVisible(true);
         
         }
        });
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList jListProduct;
    private javax.swing.JPanel jPanelPrice;
    private javax.swing.JRadioButton jRadBtn10;
    private javax.swing.JRadioButton jRadBtn15;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtPriceMax;
    private javax.swing.JTextField jTxtPriceMin;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnGenerate;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox jcmbAttribute;
    private javax.swing.JComboBox jcmbBrand;
    private javax.swing.JComboBox jcmbCategory;
    private javax.swing.JComboBox jcmbSelection;
    private javax.swing.JLabel jlblBarcode;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextField jtxtBarcode;
    // End of variables declaration//GEN-END:variables
}
